# Generated by Django 5.2.6 on 2025-09-21 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('CLIENTE', 'CLIENTE'), ('ADMIN', 'ADMIN'), ('VENDEDOR', 'VENDEDOR')], default='PENDIENTE', max_length=20)),
                ('total', models.FloatField(default=0)),
                ('seña', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('img_jugadores', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('img_arquero', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('img_auspicio1', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('img_auspicio2', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('img_auspicio3', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('img_auspicio4', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('img_auspicio5', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('talle', models.CharField(choices=[('PP', 'PP'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], max_length=3)),
                ('dorsal', models.IntegerField()),
                ('molde', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=15)),
                ('cuello_tipo', models.CharField(choices=[('REDONDO', 'REDONDO'), ('TIPO V', 'TIPO V')], max_length=50)),
                ('cuello_color', models.CharField(max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('indumentaria', models.CharField(choices=[('EQUIPO COMPLETO', 'EQUIPO COMPLETO'), ('CAMISETA SOLA', 'CAMISETA SOLA'), ('CAMISETA Y SHORT', 'CAMISETA Y SHORT')], max_length=20)),
                ('calidad', models.CharField(choices=[('ECONOMICA', 'ECONOMICA'), ('ESTANDAR', 'ESTANDAR'), ('PREMIUM', 'PREMIUM'), ('SUPER PREMIUM', 'SUPER PREMIUM')], max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_aprobado', models.FloatField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('nombre_imagen', models.CharField(blank=True, max_length=255)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_imagen', to='pedidos.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='PreciosIndumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.CharField(choices=[('ECONOMICA', 'ECONOMICA'), ('ESTANDAR', 'ESTANDAR'), ('PREMIUM', 'PREMIUM'), ('SUPER PREMIUM', 'SUPER PREMIUM')], max_length=20)),
                ('indumentaria', models.CharField(choices=[('EQUIPO COMPLETO', 'EQUIPO COMPLETO'), ('CAMISETA SOLA', 'CAMISETA SOLA'), ('CAMISETA Y SHORT', 'CAMISETA Y SHORT')], max_length=20)),
                ('precio_unitario', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('CLIENTE', 'CLIENTE'), ('ADMIN', 'ADMIN'), ('VENDEDOR', 'VENDEDOR')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
