# Generated by Django 5.2.6 on 2025-09-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('talle', models.CharField(max_length=2)),
                ('dorsal', models.IntegerField()),
                ('molde', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=15)),
                ('cuello_tipo', models.CharField(choices=[('REDONDO', 'REDONDO'), ('TIPO V', 'TIPO V')], max_length=50)),
                ('cuello_color', models.CharField(max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('calidad', models.CharField(choices=[('ECONOMICA', 'ECONOMICA'), ('ESTANDAR', 'ESTANDAR'), ('PREMIUM', 'PREMIUM')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/')),
                ('nombre_imagen', models.CharField(blank=True, max_length=255)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_imagen', to='pedidos.pedidos')),
            ],
        ),
    ]
