# Generated by Django 5.2.6 on 2025-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='seña',
            new_name='senha',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='img_senha',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pedidos/'),
        ),
        migrations.AddField(
            model_name='pedidos_detalle',
            name='tipo_jugador',
            field=models.CharField(choices=[('ARQUERO', 'ARQUERO'), ('JUGADOR', 'JUGADOR'), ('SIN DATOS', 'SIN DATOS')], default='SIN DATOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidos_detalle',
            name='indumentaria',
            field=models.CharField(choices=[('EQUIPO COMPLETO', 'EQUIPO COMPLETO'), ('CAMISETA SOLA', 'CAMISETA SOLA'), ('CAMISETA Y SHORT', 'CAMISETA Y SHORT'), ('MEDIA SOLA', 'MEDIA SOLA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preciosindumentaria',
            name='indumentaria',
            field=models.CharField(choices=[('EQUIPO COMPLETO', 'EQUIPO COMPLETO'), ('CAMISETA SOLA', 'CAMISETA SOLA'), ('CAMISETA Y SHORT', 'CAMISETA Y SHORT'), ('MEDIA SOLA', 'MEDIA SOLA')], max_length=20),
        ),
    ]
