# Generated by Django 5.2.6 on 2025-11-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_seña_pedidos_senha_pedidos_img_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_detalle',
            name='indumentaria',
            field=models.CharField(choices=[('EQUIPO COMPLETO', 'EQUIPO COMPLETO'), ('CAMISETA SOLA', 'CAMISETA SOLA'), ('CAMISETA Y SHORT', 'CAMISETA Y SHORT'), ('MEDIA SOLA', 'MEDIA SOLA'), ('SHORT SOLA', 'SHORT SOLA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preciosindumentaria',
            name='indumentaria',
            field=models.CharField(choices=[('EQUIPO COMPLETO', 'EQUIPO COMPLETO'), ('CAMISETA SOLA', 'CAMISETA SOLA'), ('CAMISETA Y SHORT', 'CAMISETA Y SHORT'), ('MEDIA SOLA', 'MEDIA SOLA'), ('SHORT SOLA', 'SHORT SOLA')], max_length=20),
        ),
    ]
