# Generated by Django 5.2.6 on 2025-11-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidos_detalle_talle'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciosindumentaria',
            name='tipo_persona',
            field=models.CharField(choices=[('NIÑOS', 'NIÑOS'), ('ADULTOS', 'ADULTOS')], default='ADULTOS', max_length=20),
        ),
    ]
