# Generated by Django 5.2.6 on 2025-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedidos_detalle_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_detalle',
            name='talle',
            field=models.CharField(choices=[('TALLE 2', 'TALLE 2'), ('TALLE 4', 'TALLE 4'), ('TALLE 6', 'TALLE 6'), ('TALLE 8', 'TALLE 8'), ('TALLE 10', 'TALLE 10'), ('TALLE 12', 'TALLE 12'), ('TALLE 14', 'TALLE 14'), ('TALLE 16', 'TALLE 16'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], max_length=10),
        ),
    ]
